### PR TITLE
Add serial number

### PR DESCRIPTION
**Pull request by cardentey**

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Thanks for the pull request! 
What will this do for people's existing automations? Does changing the serial for the device remove any existing HomeKit automations?

**Comment by cardentey** [comment]
hi, unfortunately I think it will remove any automation 😞

**Comment by Jason-Morcos** [comment]
How about tweaking it to make the serial optional and falling back on the existing hard-coded value if not specified? That would make it a non-breaking change to ease the release/migration?

**Comment by cardentey** [comment]
Hi, very good idea, I have made the changes.

**Comment by Jason-Morcos** [comment]
Looks good! Have you tested that this change will now not break any existing automations? I assume it shouldn't, but never hurts to test

**Review by Jason-Morcos — APPROVED** [review]
Should be fine, thank you for the contribution!

**Comment by darrenmcuk** [comment]
Asking a quick question….what should be the serial number format then for new sensors to do this right then?

**Comment by Jason-Morcos** [comment]
I think you should just be able to make up a random number-letter combo! Give it a try and see, let me know if you have any issues

**Pull request merged**
